import { defineConfig } from "vite"
import { resolve, dirname } from "path"
import { fileURLToPath } from "url"

const __filename = fileURLToPath(import.meta.url)
const __dirname = dirname(__filename)

const isDev = process.env.NODE_ENV === "development"
const isWatch = process.env.WATCH === "true"

export default defineConfig({
	// Set root to current directory to prevent looking for parent config
	root: __dirname,
	// Disable CSS preprocessing
	css: {
		postcss: {
			plugins: [],
		},
	},
	build: {
		lib: {
			// Entry file
			entry: resolve(__dirname, "src/index.ts"),
			// Output format: IIFE (Immediately Invoked Function Expression)
			formats: ["iife"],
			// Global variable name
			name: "IframeEditorRuntime",
			// Output filename
			fileName: () => "iframe-runtime.js",
		},
		// Output directory
		outDir: "dist",
		// Empty directory before build
		emptyOutDir: true,
		// Source map (enabled in dev/watch mode)
		sourcemap: isDev || isWatch,
		// Minify (enabled in production)
		minify: !isDev && !isWatch ? "terser" : false,
		// Terser options
		terserOptions: {
			compress: {
				drop_console: true,
				drop_debugger: true,
			},
		},
		// Watch mode
		watch: isWatch
			? {
					include: "src/**",
					exclude: "node_modules/**",
				}
			: null,
		// Rollup options
		rollupOptions: {
			external: [],
			output: {
				// Strict mode
				strict: true,
				// Banner comment
				banner: "/* iframe-runtime.js - Auto-generated by Vite */",
			},
		},
	},
	// Path alias
	resolve: {
		alias: {
			"@": resolve(__dirname, "src"),
		},
	},
})
