import type { ShortcutDefinition } from "./types"

/**
 * 系统快捷键配置
 * 所有快捷键在此集中定义
 */
export const SHORTCUTS: ShortcutDefinition[] = [
	// ===== 工具快捷键 =====
	{
		id: "tool.selection",
		name: "选择工具",
		key: "v",
		modifiers: [],
		category: "tool",
		description: "切换到选择工具",
	},
	{
		id: "tool.escape",
		name: "退出当前工具",
		key: "escape",
		modifiers: [],
		category: "tool",
		description: "退出当前工具，切换到选择工具",
	},
	{
		id: "tool.pan",
		name: "平移工具",
		key: "h",
		modifiers: [],
		category: "tool",
		isTemporary: true,
		description: "临时切换到平移工具",
	},
	{
		id: "tool.pan.space",
		name: "平移工具（空格）",
		key: "space",
		modifiers: [],
		category: "tool",
		isTemporary: true,
		description: "按住空格临时平移画布",
	},
	{
		id: "tool.text",
		name: "文本工具",
		key: "t",
		modifiers: [],
		category: "tool",
		isTemporary: true,
		description: "临时切换到文本工具",
	},
	{
		id: "tool.frame",
		name: "画框工具",
		key: "f",
		modifiers: [],
		category: "tool",
		isTemporary: true,
		description: "临时切换到画框工具",
	},
	{
		id: "tool.image-generator",
		name: "图片生成工具",
		key: "a",
		modifiers: [],
		category: "tool",
		isTemporary: true,
		description: "临时切换到图片生成工具",
	},
	{
		id: "tool.marker",
		name: "标记工具",
		key: "m",
		modifiers: [],
		category: "tool",
		isTemporary: true,
		description: "临时切换到标记工具",
	},

	// ===== 编辑快捷键 =====
	{
		id: "edit.delete",
		name: "删除",
		key: "delete",
		modifiers: [],
		category: "edit",
		preventDefault: true,
		description: "删除选中元素",
	},
	{
		id: "edit.delete.backspace",
		name: "删除（Backspace）",
		key: "backspace",
		modifiers: [],
		category: "edit",
		preventDefault: true,
		description: "删除选中元素",
	},
	{
		id: "edit.undo",
		name: "撤销",
		key: "z",
		modifiers: ["mod"],
		category: "edit",
		preventDefault: true,
		description: "撤销上一步操作",
	},
	{
		id: "edit.redo",
		name: "重做",
		key: "z",
		modifiers: ["shift", "mod"],
		category: "edit",
		preventDefault: true,
		description: "重做上一步操作",
	},
	{
		id: "edit.copy",
		name: "复制",
		key: "c",
		modifiers: ["mod"],
		category: "edit",
		preventDefault: true,
		description: "复制选中元素",
	},
	{
		id: "edit.copy-png",
		name: "复制为 PNG",
		key: "c",
		modifiers: ["shift", "mod"],
		category: "edit",
		preventDefault: true,
		description: "复制选中元素为 PNG",
	},
	{
		id: "edit.paste",
		name: "粘贴",
		key: "v",
		modifiers: ["mod"],
		category: "edit",
		preventDefault: false,
		description: "粘贴元素",
	},

	// ===== 选择快捷键 =====
	{
		id: "selection.select-all",
		name: "全选",
		key: "a",
		modifiers: ["mod"],
		category: "selection",
		preventDefault: true,
		description: "选择所有元素",
	},

	// ===== 视图快捷键 =====
	{
		id: "view.zoom-in",
		name: "放大",
		key: "+",
		modifiers: ["mod"],
		category: "view",
		preventDefault: true,
		description: "放大画布",
	},
	{
		id: "view.zoom-out",
		name: "缩小",
		key: "-",
		modifiers: ["mod"],
		category: "view",
		preventDefault: true,
		description: "缩小画布",
	},
	{
		id: "view.zoom-fit",
		name: "适应屏幕",
		key: "1",
		modifiers: ["shift"],
		category: "view",
		preventDefault: true,
		description: "缩放到适应屏幕",
	},

	// ===== 画框快捷键 =====
	{
		id: "frame.create",
		name: "创建画框",
		key: "g",
		modifiers: ["mod"],
		category: "frame",
		preventDefault: true,
		description: "为选中元素创建画框",
	},
	{
		id: "frame.remove",
		name: "移除画框",
		key: "g",
		modifiers: ["shift", "mod"],
		category: "frame",
		preventDefault: true,
		description: "移除选中元素的画框",
	},

	// ===== 对齐快捷键 =====
	{
		id: "align.left",
		name: "左对齐",
		key: "a",
		modifiers: ["alt"],
		category: "selection",
		preventDefault: true,
		description: "左对齐选中元素",
	},
	{
		id: "align.horizontal-center",
		name: "水平居中",
		key: "h",
		modifiers: ["alt"],
		category: "selection",
		preventDefault: true,
		description: "水平居中对齐",
	},
	{
		id: "align.right",
		name: "右对齐",
		key: "d",
		modifiers: ["alt"],
		category: "selection",
		preventDefault: true,
		description: "右对齐选中元素",
	},
	{
		id: "align.top",
		name: "顶部对齐",
		key: "w",
		modifiers: ["alt"],
		category: "selection",
		preventDefault: true,
		description: "顶部对齐选中元素",
	},
	{
		id: "align.vertical-center",
		name: "垂直居中",
		key: "v",
		modifiers: ["alt"],
		category: "selection",
		preventDefault: true,
		description: "垂直居中对齐",
	},
	{
		id: "align.bottom",
		name: "底部对齐",
		key: "s",
		modifiers: ["alt"],
		category: "selection",
		preventDefault: true,
		description: "底部对齐选中元素",
	},

	// ===== 分布快捷键 =====
	{
		id: "distribute.horizontal",
		name: "水平分布",
		key: "h",
		modifiers: ["shift"],
		category: "selection",
		preventDefault: true,
		description: "水平均匀分布",
	},
	{
		id: "distribute.vertical",
		name: "垂直分布",
		key: "v",
		modifiers: ["shift"],
		category: "selection",
		preventDefault: true,
		description: "垂直均匀分布",
	},
	{
		id: "distribute.auto-layout",
		name: "自动布局",
		key: "a",
		modifiers: ["shift"],
		category: "selection",
		preventDefault: true,
		description: "自动布局元素",
	},

	// ===== 层级快捷键 =====
	{
		id: "layer.move-up",
		name: "上移一层",
		key: "]",
		modifiers: ["mod"],
		category: "selection",
		preventDefault: true,
		description: "将选中元素上移一层",
	},
	{
		id: "layer.move-down",
		name: "下移一层",
		key: "[",
		modifiers: ["mod"],
		category: "selection",
		preventDefault: true,
		description: "将选中元素下移一层",
	},
	{
		id: "layer.move-to-top",
		name: "移至顶部",
		key: "]",
		modifiers: [],
		category: "selection",
		preventDefault: true,
		description: "将选中元素移至顶部",
	},
	{
		id: "layer.move-to-bottom",
		name: "移至底部",
		key: "[",
		modifiers: [],
		category: "selection",
		preventDefault: true,
		description: "将选中元素移至底部",
	},

	// ===== 可见性和锁定快捷键 =====
	{
		id: "element.toggle-visible",
		name: "切换显示/隐藏",
		key: "h",
		modifiers: ["shift", "mod"],
		category: "selection",
		preventDefault: true,
		description: "切换选中元素的显示/隐藏状态",
	},
	{
		id: "element.toggle-lock",
		name: "切换锁定/解锁",
		key: "l",
		modifiers: ["shift", "mod"],
		category: "selection",
		preventDefault: true,
		description: "切换选中元素的锁定/解锁状态",
	},

	// ===== 对话快捷键 =====
	{
		id: "conversation.add-to-current",
		name: "添加至当前对话",
		key: "l",
		modifiers: ["mod"],
		category: "selection",
		preventDefault: true,
		description: "将选中的图片添加至当前对话",
	},
]
