name: Build and push playwright-mod image

on:
  workflow_dispatch:
  push:
    paths:
      - 'thirdparty/playwright-mod/**'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: Build and push playwright-mod image
    uses: ./.github/workflows/image-build.yml
    secrets: inherit
    permissions:
      contents: write
      packages: write
      id-token: write
      attestations: write
    with:
      imageName: playwright-mod
