import { createStyles } from "antd-style"

export const useStyles = createStyles(({ token, css }) => {
	return {
		mediaViewer: {
			width: "100%",
			height: "100%",
			backgroundColor: token.colorBgBase,
			overflow: "auto",
			display: "flex",
			flexDirection: "column",
			alignItems: "center",
		},
		mediaContainer: {
			width: "100%",
			height: "calc(100% - 44px)",
			display: "flex",
			flexDirection: "column",
			alignItems: "center",
			justifyContent: "center",
			background: `${token.colorBgBlur}`,
			position: "relative",
		},
		audioWrapper: {
			width: "min(500px, calc(100% - 40px))",
			maxWidth: "100%",
			borderRadius: 12,
			padding: 20,
			background: "rgb(93,93,96)",
			boxShadow: "0 0 1px rgba(0,0,0,0.3), 0 4px 14px rgba(0,0,0,0.1)",
			display: "flex",
			alignItems: "center",
			gap: 20,
			"@media (max-width: 768px)": {
				width: "calc(100% - 20px)",
				padding: 16,
				gap: 16,
			},
		},
		controlsLeft: {
			display: "flex",
			alignItems: "center",
			gap: 10,
			flex: 1,
		},
		controlsRight: {
			display: "flex",
			alignItems: "center",
			gap: 16,
		},
		iconButton: {
			width: 20,
			height: 20,
			display: "flex",
			alignItems: "center",
			justifyContent: "center",
			color: "#fff",
			cursor: "pointer",
		},
		progressWrap: {
			display: "flex",
			alignItems: "center",
			gap: 8,
			flex: 1,
		},
		currentTime: {
			color: "#fff",
			fontSize: 12,
			lineHeight: 1.333,
			minWidth: "54px",
		},
		progress: {
			flex: 1,
			height: 24,
			display: "flex",
			alignItems: "center",
			gap: 8,
		},
		progressTrack: {
			position: "relative",
			width: "100%",
			height: 2,
			background: "#6B6D75",
			borderRadius: 100,
			cursor: "pointer",
		},
		progressFill: {
			position: "absolute",
			left: 0,
			top: 0,
			height: 2,
			background: "#fff",
			borderRadius: 100,
		},
		progressThumb: {
			position: "absolute",
			top: -4,
			width: 10,
			height: 10,
			borderRadius: 100,
			background: "#fff",
			transform: "translateX(-50%)",
			cursor: "pointer",
			"&:hover": {
				transform: "translateX(-50%) scale(1.2)",
			},
		},
		durationTime: {
			color: "#fff",
			fontSize: 12,
			lineHeight: 1.333,
			minWidth: "54px",
		},
		volumeWrap: {
			display: "flex",
			alignItems: "center",
			gap: 10,
		},
		volumeBar: {
			position: "relative",
			width: 50,
			height: 2,
			background: "#6B6D75",
			borderRadius: 100,
			cursor: "pointer",
		},
		volumeThumb: {
			position: "absolute",
			top: -4,
			left: 0,
			width: 10,
			height: 10,
			borderRadius: 100,
			background: "#fff",
			transform: "translateX(-50%)",
			cursor: "pointer",
			"&:hover": {
				transform: "translateX(-50%) scale(1.2)",
			},
		},
		// 隐藏原生音频控件
		audio: {
			display: "none",
		},
		loadingState: {
			position: "absolute",
			top: "50%",
			left: "50%",
			transform: "translate(-50%, -50%)",
			color: "#fff",
			fontSize: 14,
			display: "flex",
			alignItems: "center",
			justifyContent: "center",
		},
		errorState: {
			position: "absolute",
			top: "50%",
			left: "50%",
			transform: "translate(-50%, -50%)",
			color: "#ff6b6b",
			fontSize: 14,
			display: "flex",
			alignItems: "center",
			justifyContent: "center",
			textAlign: "center",
			maxWidth: "80%",
		},
	}
})
