import { createStyles } from "antd-style"

export const useStyles = createStyles(({ token }) => {
	return {
		container: {
			width: "100vw",
			height: "100vh",
			backgroundColor: "#F9F9F9",
			display: "flex",
			flexDirection: "column",
			overflow: "hidden",
		},
		header: {
			display: "flex",
			alignItems: "center",
			justifyContent: "space-between",
			padding: "10px 20px",
			height: "48px",
			background: "#fff",
			backdropFilter: "blur(50px)",
			borderBottom: `1px solid ${token.colorBorder}`,
			zIndex: 99,
			"@media (max-width: 768px)": {
				height: `calc(52px + ${token.safeAreaInsetTop})`,
				padding: `${token.safeAreaInsetTop} 12px 0px 12px`,
			},
		},
		logo: {
			height: "42px",
			flexShrink: 0,
			"@media (max-width: 768px)": {
				height: "36px",
			},
		},
		content: {
			flex: 1,
			display: "flex",
			alignItems: "center",
			justifyContent: "center",
			padding: "20px",
		},
		main: {
			display: "flex",
			flexDirection: "column",
			alignItems: "center",
			gap: "20px",
			maxWidth: "400px",
			width: "100%",
		},
		icon: {
			width: "60px",
			height: "60px",
			flexShrink: 0,
		},
		title: {
			fontFamily: "PingFang SC",
			fontSize: "18px",
			fontWeight: 600,
			lineHeight: "24px",
			textAlign: "center",
			color: token.magicColorUsages.text[1],
		},
		card: {
			display: "flex",
			flexDirection: "column",
			alignSelf: "stretch",
			gap: "20px",
			padding: "20px",
			backgroundColor: "#FFFFFF",
			borderRadius: "12px",
			border: "1px solid rgba(28, 29, 35, 0.08)",
		},
		cardContent: {
			display: "flex",
			flexDirection: "column",
			alignItems: "center",
			alignSelf: "stretch",
			gap: "8px",
		},
		tip: {
			fontFamily: "PingFang SC",
			fontSize: "12px",
			fontWeight: 400,
			lineHeight: "16px",
			textAlign: "center",
			color: "rgba(28, 29, 35, 0.6)",
			alignSelf: "stretch",
		},
		userInfo: {
			display: "flex",
			alignItems: "center",
			gap: "4px",
		},
		avatarContainer: {
			width: "24px",
			height: "24px",
			borderRadius: "6px",
			backgroundColor: "#DDE7FF",
			display: "flex",
			alignItems: "center",
			justifyContent: "center",
			padding: "1.5px",
			flexShrink: 0,
		},
		avatar: {
			width: "24px",
			height: "24px",
			borderRadius: "6px",
		},
		userName: {
			fontFamily: "PingFang SC",
			fontSize: "14px",
			fontWeight: 600,
			lineHeight: "20px",
			color: token.magicColorUsages.text[0],
		},
		button: {
			display: "flex",
			justifyContent: "center",
			alignItems: "center",
			alignSelf: "stretch",
			padding: "6px 24px",
			height: "auto",
			backgroundColor: token.colorPrimary,
			borderRadius: "8px",
			border: "none",
			fontSize: "14px",
			fontWeight: 400,
			lineHeight: "20px",
			color: "#FFFFFF",
			cursor: "pointer",
			"&:hover": {
				backgroundColor: token.colorPrimaryHover,
			},
			"&:disabled": {
				backgroundColor: token.colorBgTextActive,
				cursor: "not-allowed",
			},
		},
	}
})
